Fixes two errors (model_fittings.kinematics value & click package)
This commit fixes for two errors:

- When the default value of model_fittings.kinematics is None results to an error. This happens when the application runs for the first time in initialization modes of 'Event' or 'Manual'. This resulted to an error when the kinematics plots was selected.

- Updates the requirements. Because of the following error from the click package: AttributeError: module 'click' has no attribute 'get_os_args'. Streamlit corrects this in version 1.8.1. For previous verisions "pip install -U click==8".